<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/7/9
 * Time: 13:43
 */

namespace app\admin\controller;

use app\admin\controller\Admin;
use app\admin\model\Article as Articles;

class Article extends Admin
{
    private $_model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function type()
    {
        $map = [
            'status'    =>  1
        ];
        $list = db('type')->where($map)->select();
        $this->assign('list',$list);
        return $this->fetch();
    }

    public function index()
    {
        return $this->fetch();
    }

    public function articleList()
    {
        $this->_model = new Articles();
        $list = $this->_model->select();
        if ($list) {
            $list = collection($list)->toArray();
        }
        $count = count($list);
        echo json_encode(array(
            'code'  =>  0,
            'msg'   =>  '',
            'data'  =>  $list,
            'count' =>  $count
        ));
    }

    public function add()
    {
        if (request()->isPost()) {
            $data = [];
            $data['title'] = input('post.title');
            $data['logo'] = input('post.logo');
            $data['content'] = input('post.content');
            $data['author'] = cookie('name') ? cookie('name') : 'SoySauce';

            $this->_model = new Articles();
            $res = $this->_model->validate('Article.add')->allowField(true)->save($data);

            if ($res) {
                return json_data('操作成功','',1);
            }
            return json_data($this->_model->getError());
        } else {
            return $this->fetch();
        }
    }

    public function test()
    {
        return $this->fetch();
    }

    public function upload()
    {
        /*
         * TODO::乙方logo上传
         * */
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file('file');

        // 移动到框架应用根目录/public/uploads/ 目录下
        if ($file) {
            $info = $file->move(ROOT_PATH . 'public'. DS  .'static' . DS . 'Upload'. DS );
            if ($info) {
                // 成功上传后 获取上传信息
                // 输出 jpg
                $info->getExtension();
                // 输出 20160820/42a79759f284b767dfcb2a0197904287.jpg
                $name = str_replace('\\','/',$info->getSaveName());
                return json_data('/Upload/'.$name,'',1);
                // 输出 42a79759f284b767dfcb2a0197904287.jpg
                echo $info->getFilename();
            } else {
                // 上传失败获取错误信息
                return json_data("上传失败");
            }
        } else {
            return json_data("文件不存在");
        }
    }
}