<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/8/10
 * Time: 10:43
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\model\Banner as Banners;

class Banner extends Admin
{
    private $_model;
    public function _initialize()
    {
        $this->_model = new Banners();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $banner = $this->_model->select();
        $this->assign('banner',$banner);
        return $this->fetch();
    }

    public function add()
    {
        $data = input('post.');
        if (!$data['desc'] || !$data['image']) {
            return json_data();
        }

        if ($this->_model->insert($data)) {
            return json_data('添加成功','',1);
        }
        return json_data();
    }
}