<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/7/5
 * Time: 17:29
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\controller\Configure as Configs;
use app\admin\model\Email;

class Configure extends Admin
{
    private $_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Title   alipay
     * @Description todo::alipay details
     * @Time    2018年7月6日16:12:39
     * */
    public function alipay()
    {
        $map = [
            'name'  =>  'alipay'
        ];
        $alipay = db('alipay')->where($map)->find();
        $this->assign('alipay',$alipay);

        return $this->fetch();
    }

    /**
     * @Title   aliEdit
     * @Description todo::edit alipay infomations
     * @Time    2018年7月6日16:13:35
     * */
    public function aliEdit()
    {
        $id = input('get.');
        $data = input('post.');
        if (!$id) {
            return json_data();
        }
        $this->_model = new Configs();
        $res = $this->_model->validate(true)->allowField(true)->save($data,['id'=>$id]);
        if ($res) {
            return json_data('操作成功','',1);
        }
        return json_data($this->_model->getError());
    }

    /**
     * @Title   email
     * @Description todo::email config details list
     * @Time    2018年7月6日16:14:27
     * */
    public function email()
    {
        $map = [
            'status'    =>  1
        ];
        $model = new Email();
        $email = $model->where($map)->select();
        $this->assign('email',$email);

        return $this->fetch();
    }

    /**
     * @Title   emailEdit
     * @Description todo::  add or edit email's config infomation
     * @Time    2018年7月6日16:15:42
     * */
    public function emailEdit()
    {
        $oper = input('get.oper');
        $model = new Email();
        $data = input('post.');

        if ($oper == 'edit') {
            $id = input('get.id');
            $res = $model->validate('Email.edit')->allowField(true)->isUpdate(true)->save($data,['id'=>$id]);
        } else {
            $res = $model->validate('Email.add')->allowField(true)->isUpdate(false)->save($data);
        }
        if ($res !== false) {
            return json_data('操作成功','',1);
        }
        return json_data($model->getError());
    }

    /**
     * @Title   emailStatus
     * @Description todo::update email status
     * @Time    2018年7月6日16:16:51
     * */
    public function emailStatus()
    {
        $id = input('get.id');
        if (!$id) {
            return json_data();
        }
        $status = input('get.status') ? input('get.status') : 0;
        $data = [
            'status'    =>  $status
        ];
        $model = new Email();
        $res = $model->where('id',$id)->update($data);
        if ($res !== false) {
            return json_data('操作成功');
        }
        return json_data();
    }

    /**
     * @TItle   emailDel
     * @Description todo::delete email
     * @Time    2018年7月6日16:17:37
     * */
    public function emailDel()
    {
        $id = input('get.id');
        if (!$id) {
            return json_data();
        }
        $model = new Email();
        $map = ['id' => $id];
        if ($model->where($map)->delete()) {
            return json_data('操作成功','',1);
        }
        return json_data();
    }

    public function index()
    {
        return $this->fetch();
    }
}