<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/6/29
 * Time: 11:04
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\model\Icon as Icons;

class Icon extends Admin
{
    private  $_model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->_model = new Icons();
        $data['icon'] = input('get.icon');
        $window = input('get.window');
        $data['list'] = cache('icon_list');
        if (!$data['list']) {
            $this->_model->_fields = "classname";
            $data['list'] = $this->_model->field($this->_model->_fields)->select();
            cache('icon_list',$data['list']);
        }
        $this->assign('window',$window);
        $this->assign('data',$data);
        return $this->fetch();
    }
}