<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/6/26
 * Time: 10:11
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;

class Index extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }

    public function body()
    {
        return $this->fetch();
    }
}