<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/8/8
 * Time: 11:19
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\model\Label as Labels;

class Label extends Admin
{
    private $_model;
    public function _initialize()
    {
        $this->_model = new Labels();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $label = $this->_model->select();
        if ($label) {
            $label = collection($label)->toArray();
        }
        $this->assign('label',$label);
        return $this->fetch();
    }

    public function add()
    {
        $name = input('post.name');
        if (!$name) {
            return json_data();
        }

        $data = [
            'name'  =>  $name
        ];
        if ($this->_model->insert($data)) {
            return json_data('添加成功','',1);
        }
        return json_data();
    }
}