<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/6/26
 * Time: 17:50
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\model\Menu as Menus;
use app\admin\model\Admin as Admins;
use app\admin\validate\Menu as MenuV;

class Menu extends Admin
{
    private $_model;
    public function _initialize()
    {
        $this->_model = new Menus();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $menuList = array();
        $this->assign('menuList',$menuList);
        return $this->fetch();
    }

    function test()
    {
        return $this->fetch();
    }

    public function add()
    {
        if (request()->isPost()) {
            $data = input('post.');
            $menuV = new MenuV();
            $result = $menuV->scene('add')->check($data);
            if (!$result) {
                return json_data($menuV->getError());
            }

            $res = $this->_model->allowField(true)->save($data);
            if ($res) {
                return json_data('添加成功','',1);
            }
            return json_data();
        } else {
            $modules = $this->modules();
            $this->assign('modules',$modules);
            return $this->fetch();
        }
    }

    public function edit()
    {
        $id = input('get.id');
        if (!$id) {
            return json_data();
        }
        $data = input('post.');
        $menuV = new MenuV();
        $result = $menuV->scene('edit')->check($data);
        if (!$result) {
            return json_data($menuV->getError());
        }

        $res = $this->_model->isUpdate(true)->allowField(true)->save($data, ['id' => $id]);
        if ($res !== false) {
            cache('menu_list_'.$this->_admin_id,null);
            return json_data('编辑成功', '', 1);
        }
        return json_data();
    }

    public function menuList()
    {
        $menu = cache('menu_list_'.$this->_admin_id);
        if (!$menu) {
            $this->_model->_where['status'] = 1;
//            $amodel = new Admins();
//            $amodel->_where['id'] = $this->_admin_id;
//            $this->_model->_where['status'] = 1;
            $menu = $this->_model->where($this->_model->_where)->select();
            cache('menu_list_'.$this->_admin_id,$menu,3600);
        }

        return json_data($menu);
    }


    public function modules()
    {
        $list = cache('modules_list'.$this->_admin_id);
        if (!$list) {
            $this->_model->_where['status'] = 1;
            $this->_model->_fields = "id,name";
            $list = $this->_model->field($this->_model->_fields)->where($this->_model->_where)->select();
            $list = $list ? collection($list)->toArray() : $list;
            cache('modules_list'.$this->_admin_id,$list,0);
        }
        return $list;
    }

    public function del()
    {
        $id = input('get.id');
        if (!$id) {
            return json_data();
        }
        $map = ['id'=>$id];
        if ($this->_model->where($map)->delete()) {
            return json_data('操作成功');
        }
        return json_data();
    }
}