<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/6/26
 * Time: 19:34
 */

namespace app\admin\controller;

use app\admin\controller\Admin as Admin;
use app\admin\model\Role as Roles;

class Role extends Admin
{
    private $_model;
    public function _initialize()
    {
        $this->_model = new Roles();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $roles = $this->_model->select();
        if ($roles) {
            $roles = collection($roles)->toArray();
        }

        $this->assign('role',$roles);
        return $this->fetch();
    }

    public function create()
    {
        $data = input('post.');
        $res = $this->_model->validate('Role.create')->allFlow(true)->isUpdate(false)->save($data);
        if (!$res) {
            return json_data();
        }
        return json_data('添加成功');
    }

    public function edit()
    {
        $data = input('post.');
        if (!isset($data['id']) || !$data['id']) {
            return json_data();
        }
        $this->_model->_where['id'] = $data['id'];
        $res = $this->_model->validate('Role.create')->where($this->_model->_where)
                    ->allFlow(true)->isUpdate(false)
                    ->save($data);
        if ($res !== false) {
            return json_data('','',1);
        }
        return json_data();
    }
}