<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/7/13
 * Time: 18:01
 */

namespace app\admin\controller;

use think\Controller;
use app\admin\model\Test as Tests;

class Test extends Controller
{
    private $_model;
    public function _initialize()
    {
        $this->_model = new Tests();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        set_time_limit(0);
        $data = array();
        $string = '卸航衣孙龄岭骗休借';
        $length = mb_strlen($string);
        for ($i = 0;$i < 1000000;$i ++) {
            $start = mt_rand(0,$length);
            $data['name'] = mb_substr($string,$start,10);
            $data['score'] = mt_rand(10000,999999);
            $data['desc'] = mb_substr($string,$start,40);
            $data['create_time'] = time();
            $this->_model->insert($data);
        }

        return 1;
    }

    public function test1()
    {
        ob_end_clean();//关闭缓存
        set_time_limit(0);
        ob_implicit_flush(); //这个语句将强制每当有输出就自动刷新，相当于在每个echo后，调用ob_flush()
        $new_mesg = NULL;
        register_tick_function("test_data");
        $new_mesg = test_data();
        declare(ticks=1){
            while(1){
                if(!is_null($new_mesg)){
                    foreach($new_mesg as $msg){
                        echo $msg;
                    }
                    $new_mesg = null;
                }
            }
        }
    }

}