<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/7/3
 * Time: 10:02
 */

namespace app\api\controller;

use think\Controller;

class Api extends Controller
{
    private $_apiStr = "jiawang14155";
    public function _initialize()
    {
        $data = input('post.');
        if (!isset($data['apikey']) || !isset($data['sign']) || !$data['apikey'] || !$data['sign']) {
            return api_json(array(),'参数错误',101,'ParamErr');
        }
        $sign = md12345($data['timestamp'].$this->_apiStr);

        if ($sign != $data['sign']) {
            return api_json(array(),'签名错误',102,'ParamErr');
        }

        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}