<?php
/**
 * Created by PhpStorm.
 * User: wangjia
 * Date: 2018/7/3
 * Time: 9:59
 */

namespace app\api\controller;

use app\api\controller\Api as Api;
use PHPMailer\PHPMailer\PHPMailer;

class Mail extends Api
{
    private $_attachment = null;//
    private $_subject = '';//
    private $_body='';//邮件内容
    private $_tomail;//收件人
    private $_name;//发件人姓名
    private $_host;//SMTP 服务器
    private $_username;//SMTP服务器用户名
    private $_password;//SMTP服务器密码
    private $_send_name;//收件人姓名

    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function sendMail()
    {
        $this->_tomail = input('post.tomail') ? input('post.tomail') : '';
        if ($this->_tomail == '') {
            return api_json(array(),'邮件地址不能为空',103,'ParamErr');
        }
        $this->_body =  input('post.body') ? input('post.body') : '';
        $this->_body = " <html><head><title>This is a test</title></head><body><p>Dear all,</p><p>This is a test for HTML mail sending.</p></body></html> ";
        if ($this->_body == '') {
            return api_json(array(),'邮件内容不能为空',103,'ParamErr');
        }
        $this->_subject = input('post.subject') ? input('post.subject') : '';
        $type = input('post.type') ? input('post.type') : 'QQ';
        $this->_host = config('MAIL_HOST_'.$type);
        $this->_username = config('MAIL_USER_NAME_'.$type);
        $this->_password = config('MAIL_PASSWORD_'.$type);
        $this->_send_name = config('MAIL_SEND_NAME_'.$type);
        $this->_name = config('MAIL_NAME_'.$type);

        if ($this->send()) {
            return api_json(array(),'发送成功',200,'Success');
        }
        return api_json(array(),'发送失败',100,'Failed');
    }
    /**
     * 邮件发送函数
     * $to 邮箱
     * $title 标题
     *  $content 内容
     */
    public function send()
    {
        set_time_limit(0);
        $mail = new PHPMailer();           //实例化PHPMailer对象
        $mail->CharSet = 'UTF-8';           //设定邮件编码，默认ISO-8859-1，如果发中文此项必须设置，否则乱码
        $mail->IsSMTP();                    // 设定使用SMTP服务
        $mail->SMTPDebug = 0;               // SMTP调试功能 0=关闭 1 = 错误和消息 2 = 消息
        $mail->SMTPAuth = true;             // 启用 SMTP 验证功能
        $mail->SMTPSecure = 'ssl';          // 使用安全协议
        $mail->Host = $this->_host; // SMTP 服务器
        $mail->Port = 465;                  // SMTP服务器的端口号
        $mail->Username = $this->_username;    // SMTP服务器用户名
        $mail->Password = $this->_password;     // SMTP服务器密码
        $mail->SetFrom($this->_send_name, $this->_name);
        $replyEmail = '';                   //留空则为发件人EMAIL
        $replyName = '';                    //回复名称（留空则为发件人名称）
        $mail->AddReplyTo($replyEmail, $replyName);
        $mail->Subject = $this->_subject;
        $mail->MsgHTML($this->_body);
        $mail->AddAddress($this->_tomail, $this->_name);
        if (is_array($this->_attachment)) { // 添加附件
            foreach ($this->_attachment as $file) {
                is_file($file) && $mail->AddAttachment($file);
            }
        }

        if ($mail->send()) {
            return true;
        }

        return false;
    }
}